import { Question } from '@/features/onboarding/types';

export const studentOnboardingQuestions: Question[] = [
  {
    id: '1',
    question_text: 'Which activities sound most fun to you?',
    question_type: 'multi_choice',
    category: 'onboarding',
    options: [
      'Designing or creating something new',
      'Solving puzzles, fixing gadgets, or coding',
      'Leading projects or persuading others',
      'Helping friends or teaching others',
      'Organizing schedules or data',
    ],
    target_field: 'interests',
    user_types: ['student'],
    order: 1,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '2',
    question_text: 'Which school subjects do you enjoy most?',
    question_type: 'multi_choice',
    category: 'onboarding',
    options: [
      'Arts / Literature',
      'Math / Science',
      'Social Studies / Leadership activities',
      'PE / Volunteering / Helping roles',
      'Business / Economics',
    ],
    target_field: 'interests',
    user_types: ['student'],
    order: 2,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '3',
    question_text: 'What kind of skills do you feel most confident in?',
    question_type: 'multi_choice',
    category: 'onboarding',
    options: [
      'Creativity / Expression',
      'Problem-solving / Analysis',
      'Communication / Leadership',
      'Caring / Mentoring',
      'Organization / Planning',
    ],
    target_field: 'skills',
    user_types: ['student'],
    order: 3,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '4',
    question_text: 'What’s most important for your future career?',
    question_type: 'single_choice',
    category: 'onboarding',
    options: [
      'High salary',
      'Job stability',
      'Creativity and freedom',
      'Helping others / Making impact',
      'Prestige / Recognition',
    ],
    target_field: 'career_goals',
    user_types: ['student'],
    order: 4,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '5',
    question_text: 'How do you like to learn best?',
    question_type: 'single_choice',
    category: 'onboarding',
    options: [
      'Trying it myself first',
      'Working with classmates / mentors',
      'Watching examples then copying',
      'Following clear step-by-step instructions',
    ],
    target_field: 'learning_style',
    user_types: ['student'],
    order: 5,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '6',
    question_text: 'In the next 5 years, I’d like to…',
    question_type: 'single_choice',
    category: 'onboarding',
    options: [
      'Start a business or project',
      'Get a stable job right after graduation',
      'Take more studies / certifications',
      'Explore different paths until I find my fit',
    ],
    target_field: 'career_aspirations',
    user_types: ['student'],
    order: 6,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
];

export const professionalOnboardingQuestions: Question[] = [
  {
    id: '7',
    question_text: 'Which part of your current work do you enjoy most?',
    question_type: 'multi_choice',
    category: 'onboarding',
    options: [
      'Creating / designing ideas',
      'Solving problems with tools or data',
      'Leading teams / making decisions',
      'Supporting others / customer service',
      'Organizing / streamlining processes',
    ],
    target_field: 'work_enjoyment',
    user_types: ['professional'],
    order: 1,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '8',
    question_text: 'Which part feels least “you”?',
    question_type: 'multi_choice',
    category: 'onboarding',
    options: [
      'Routine / repetitive work',
      'Technical tasks',
      'Leadership roles',
      'People-facing tasks',
      'Creative work',
    ],
    target_field: 'work_dislikes',
    user_types: ['professional'],
    order: 2,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '9',
    question_text: 'What motivates you most now?',
    question_type: 'single_choice',
    category: 'onboarding',
    options: [
      'Higher income',
      'Work-life balance',
      'Learning and growth',
      'Social impact / purpose',
      'Prestige / recognition',
    ],
    target_field: 'motivation',
    user_types: ['professional'],
    order: 3,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '10',
    question_text: 'What environment do you prefer?',
    question_type: 'single_choice',
    category: 'onboarding',
    options: [
      'Independent work',
      'Team collaboration',
      'Leadership & decision-making',
      'Research and analysis',
      'Helping/support roles',
    ],
    target_field: 'work_environment',
    user_types: ['professional'],
    order: 4,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '11',
    question_text: 'Which skill would you most like to strengthen?',
    question_type: 'multi_choice',
    category: 'onboarding',
    options: [
      'Technical / digital',
      'Communication / leadership',
      'Creativity / innovation',
      'People / service skills',
      'Organization / management',
    ],
    target_field: 'skill_development',
    user_types: ['professional'],
    order: 5,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
  {
    id: '12',
    question_text: 'In the next 2–3 years, I’d like to…',
    question_type: 'single_choice',
    category: 'onboarding',
    options: [
      'Shift careers completely',
      'Move up in my current field',
      'Start my own venture',
      'Pursue further studies or certifications',
      'Explore options until I find a good fit',
    ],
    target_field: 'future_aspirations',
    user_types: ['professional'],
    order: 6,
    active: true,
    processing_type: 'direct',
    stage: 'onboarding',
  },
];
