#!/bin/sh

echo '👷‍♂️ Starting pre-commit checks...'

echo '🎨 Formatting ...'
bun run format || {
  echo '❌ Formatting failed.'
  exit 1
}

echo '🧹 Linting ...'
bun run lint || {
  echo '❌ Linting failed. Please fix the errors before committing.'
  exit 1
}

# Add staged files back after formatting
git add .

echo '✅ All pre-commit checks passed. Proceeding with commit. 🚀'